## Basic Configuration
baseurl = "https://adeshinahassan.com/"
languageCode = "en"

title = "Adeshina"
theme = "novela"

## Taxonomies
[taxonomies]
tag = "tags"
category = "categories"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
enableRobotsTXT = true
pygmentsStyle = "github"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

# summarylength = 30
paginate = 6

## Markup Configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "github"
    tabWidth = 4

## Ignore Logs for Raw HTML Warnings
ignoreLogs = ['warning-goldmark-raw-html']

## Site Settings
[params]
    author = "Adeshina"
    title = "Software Engineer"
    description = "Software Engineer"
    authorimage = "img/avatar.png"
    dateformat = "Jan 2, 2006"
    keywords = "blog, developer, engineering, go, golang, flutter, devOps, frontend, backend"
    info = "WEB AND APPS ENGINEER"
    fixedbarContent = "Do you want to know me more private?→"
    fixedbarContentAfter = "Thank You! Please share it if you like it→"
    snsShare = true
    enableTwitterShare = true
    enableFacebookShare = true
    itemscentered = true
    langseparator = "|"
    themeColor = "theme-base-0d"



    # sidebar, copyright & license
    copyright = "Adeshina"
    # showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    #highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts for Novela Theme
[params.social]
    medium = "https://medium.com/@adeshinaHH"
    github = "https://github.com/d-sense"
    linkedin = "https://linkedin.com/in/adesina-hammed-h-7bb52372"
    twitter = "https://twitter.com/adeshinaHH"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
