## Basic Configuration
baseurl = "https://adeshinahassan.com"
languageCode = "en"

title = "Adeshina"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Adeshina"
    title = "Software Engineer"
    description = "Software Engineer"
    authorimage = "/img/avatar.png"
    dateformat = "Jan 2, 2006"
    keywords = "blog,developer,engineering, go, golang, flutter, devOps, frontend, backend"
    info = "WEB AND APPS ENGINEER"
    fixedbarContent = "Do you want to know me more private?→"
    fixedbarContentAfter = "Thank You! Please share it if you like it→"
    snsShare = true
    enableTwitterShare = true
    enableFacebookShare = true
    itemscentered = true
    langseparator = "|"
    themeColor = "theme-base-0d"



    # sidebar, copyright & license
    copyright = "Adeshina"
    # showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    #highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "d-sense"
    linkedin = "adesina-hammed-h-7bb52372"
    twitter = "delameh"
    email = "delameh@icloud.com"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
