[build]
publish = "public"
command = "hugo --minify"

[build.environment]
HUGO_VERSION = "0.148.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "18"

[context.production.environment]
HUGO_VERSION = "0.148.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "18"

[context.deploy-preview.environment]
HUGO_VERSION = "0.148.2"
HUGO_ENV = "production"
NODE_VERSION = "18"

[context.branch-deploy.environment]
HUGO_VERSION = "0.148.2"
HUGO_ENV = "production"
NODE_VERSION = "18"