[build]
publish = "public"
command = "hugo --minify --baseURL https://adeshinahassan.com/"

[context.production.environment]
HUGO_VERSION = "0.121.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "18"

[build.environment]
HUGO_VERSION = "0.121.0"
NODE_VERSION = "18"